In [12]:
from constants import *
games = read_csv('games.csv')

In [2]:
games.head()

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
0,2222597,RU1,2012,6. Matchday,2012-08-25,3725,232,2,1,2.0,...,Akhmat-Arena,21700.0,Vladislav Bezborodov,https://www.transfermarkt.co.uk/terek-grozny_s...,NaN,NaN,RFK Akhmat Grozny,FK Spartak Moskva,2:1,domestic_league
1,2222627,RU1,2012,5. Matchday,2012-08-20,2696,4128,0,2,11.0,...,Metallurg,11400.0,Sergey Ivanov,https://www.transfermarkt.co.uk/krylya-sovetov...,NaN,NaN,PFK Krylya Sovetov Samara,Amkar Perm,0:2,domestic_league
2,2222658,RU1,2012,10. Matchday,2012-09-30,2410,121,0,2,2.0,...,Arena Khimki,12000.0,Sergey Karasev,https://www.transfermarkt.co.uk/cska-moscow_di...,NaN,NaN,PFK CSKA Moskva,FK Dinamo Moskva,0:2,domestic_league
3,2222664,RU1,2012,8. Matchday,2012-09-15,932,2698,1,0,5.0,...,RZD Arena,11408.0,Sergey Karasev,https://www.transfermarkt.co.uk/lokomotiv-mosc...,NaN,NaN,"Футбольный клуб ""Локомотив"" Москва",FC Rubin Kazan,1:0,domestic_league
4,2222683,RU1,2012,12. Matchday,2012-10-22,2696,12438,0,1,11.0,...,Metallurg,7534.0,Timur Arslanbekov,https://www.transfermarkt.co.uk/krylya-sovetov...,NaN,NaN,PFK Krylya Sovetov Samara,Volga Nizhniy Novgorod (- 2016),0:1,domestic_league

In [13]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65216 entries, 0 to 65215
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   game_id                 65216 non-null  int64
 1   competition_id          65216 non-null  object
 2   season                  65216 non-null  int64
 3   round                   65216 non-null  object
 4   date                    65216 non-null  object
 5   home_club_id            65216 non-null  int64
 6   away_club_id            65216 non-null  int64
 7   home_club_goals         65216 non-null  int64
 8   away_club_goals         65216 non-null  int64
 9   home_club_position      45762 non-null  float64
 10  away_club_position      45762 non-null  float64
 11  home_club_manager_name  64474 non-null  object
 12  away_club_manager_name  64474 non-null  object
 13  stadium                 65005 non-null  object
 14  attendance              55704 non-null  float64
 15  referee                 64622 non-null  object
 16  url                     65216 non-null  object
 17  home_club_formation     2869 non-null   object
 18  away_club_formation     2888 non-null   object
 19  home_club_name          53964 non-null  object
 20  away_club_name          55167 non-null  object
 21  aggregate               65216 non-null  object
 22  competition_type        65216 non-null  object
dtypes: float64(3), int64(6), object(14)
memory usage: 11.4+ MB

In [4]:
n_c = null_columns(games)
n_c

['home_club_position',
 'away_club_position',
 'home_club_manager_name',
 'away_club_manager_name',
 'stadium',
 'attendance',
 'referee',
 'home_club_formation',
 'away_club_formation',
 'home_club_name',
 'away_club_name']

In [9]:
games.to_csv(DATA_FOLDER + 'new_games.csv', index=False)

In [7]:
null_columns(read_csv('new_games.csv'))

['home_club_position',
 'away_club_position',
 'stadium',
 'attendance',
 'referee',
 'home_club_formation',
 'away_club_formation']

In [8]:
set(games['competition_type'])

{'domestic_cup', 'domestic_league', 'international_cup', 'other'}

In [11]:
games.describe()

,game_id,season,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,away_club_position,attendance
count,6.521600e+04,65216.000000,65216.000000,65216.000000,65216.000000,65216.000000,45762.000000,45762.000000,55704.000000
mean,3.018125e+06,2017.252990,4921.579597,4441.948862,1.593290,1.321440,9.273043,9.456776,18060.337337
std,5.605215e+05,3.348529,11440.848691,10262.628710,1.427243,1.363181,5.299837,5.321858,17764.667425
min,2.211607e+06,2012.000000,1.000000,2.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,2.518596e+06,2014.000000,354.000000,347.000000,1.000000,0.000000,5.000000,5.000000,4300.000000
50%,2.919854e+06,2017.000000,995.000000,989.000000,1.000000,1.000000,9.000000,9.000000,12140.000000
75%,3.450800e+06,2020.000000,3205.000000,3028.000000,2.000000,2.000000,14.000000,14.000000,26184.000000
max,4.228114e+06,2023.000000,112753.000000,112755.000000,15.000000,19.000000,21.000000,21.000000,99354.000000

In [8]:
#i want to delete every game that has a home_club_id referring to a club that is not in the clubs.csv file, same thing for away_club_id
clubs = read_csv('clubs.csv')
clubIDS = set(clubs['club_id'])
games = games[games['home_club_id'].isin(clubIDS) & games['away_club_id'].isin(clubIDS)]

In [11]:
new_games = pd.read_json(f'{JSON_DATA_FOLDER}new_games.json')
new_games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51642 entries, 0 to 51641
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   game_id                 51642 non-null  int64
 1   competition_id          51642 non-null  object
 2   season                  51642 non-null  int64
 3   round                   51642 non-null  object
 4   date                    51642 non-null  datetime64[ns]
 5   home_club_id            51642 non-null  int64
 6   away_club_id            51642 non-null  int64
 7   home_club_goals         51642 non-null  int64
 8   away_club_goals         51642 non-null  int64
 9   home_club_position      45762 non-null  float64
 10  away_club_position      45762 non-null  float64
 11  home_club_manager_name  51456 non-null  object
 12  away_club_manager_name  51456 non-null  object
 13  stadium                 51593 non-null  object
 14  attendance              45065 non-null  float64
 15  referee                 51466 non-null  object
 16  url                     51642 non-null  object
 17  home_club_formation     1853 non-null   object
 18  away_club_formation     1853 non-null   object
 19  home_club_name          51642 non-null  object
 20  away_club_name          51642 non-null  object
 21  aggregate               51642 non-null  object
 22  competition_type        51642 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(6), object(13)
memory usage: 9.1+ MB